"""
Risk:Reward Profitability Analysis
"""

print('='*80)
print('RISK:REWARD PROFITABILITY ANALYSIS')
print('='*80)

print('\n### Understanding the 3:1 Risk:Reward Ratio:')
print('  - Every WIN captures +3R (3x the risk amount)')
print('  - Every LOSS captures -1R (1x the risk amount)')
print('  - Break-even win rate needed: 25% (1 win covers 3 losses)')
print('  - Profit zone: Win rate > 25%')

print('\n### Performance vs Break-Even:')
print()
print(f'{"Asset":<12} | {"Win Rate":<9} | {"Wins":<5} | {"Losses":<7} | {"Net R":<8} | {"Required Wins":<14} | {"Status"}')
print('-'*95)
print(f'{"XAG_USD":<12} | {"55.6%":<9} | {5:<5} | {4:<7} | {"+11.0 R":<8} | {"2.25 (had 5)":<14} | {"PROFITABLE":<15}')
print(f'{"WHEAT_USD":<12} | {"28.1%":<9} | {9:<5} | {23:<7} | {"+4.0 R":<8} | {"7.67 (had 9)":<14} | {"MARGINAL":<15}')
print(f'{"BCO_USD":<12} | {"26.7%":<9} | {8:<5} | {22:<7} | {"+2.0 R":<8} | {"7.33 (had 8)":<14} | {"MARGINAL":<15}')

print('\n### Why WHEAT and BCO Lost Money Despite Positive R:')
print('  Although they had slightly positive R multiples (+4.0 R and +2.0 R),')
print('  the SPREAD COST of 0.06% per trade eroded profits:')
print()
print(f'  WHEAT: 32 trades x ~$8 spread cost = ~$256 total spread cost')
print(f'         Gross R profit: +4.0 R approximately +$32 (before spread)')
print(f'         After spread: -$5.09 actual loss')
print()
print(f'  BCO:   30 trades x ~$7.50 spread cost = ~$225 total spread cost')
print(f'         Gross R profit: +2.0 R approximately +$20 (before spread)')
print(f'         After spread: -$16.85 actual loss')

print('\n### XAG Success Factors:')
print('  1. High win rate (55.6%) - well above break-even 25%')
print('  2. Fewer total trades (9) = lower cumulative spread cost (~$72)')
print('  3. Strong R multiple (+11.0 R) absorbed spread costs easily')
print('  4. SilverSniper 5m strategy has better entry precision')

print('\n### Profitability Threshold Calculator:')
print('  For 3:1 R:R with 0.06% spread cost:')
print()
print(f'  {"Trades":<8} | {"Min Win Rate":<13} | {"Example: Wins/Losses":<25} | {"Expected Profit"}')
print('-'*80)
print(f'  {"10":<8} | {"27%":<13} | {"3 wins / 7 losses":<25} | {"+$10 to +$20"}')
print(f'  {"20":<8} | {"28%":<13} | {"6 wins / 14 losses":<25} | {"+$15 to +$30"}')
print(f'  {"30":<8} | {"30%":<13} | {"9 wins / 21 losses":<25} | {"Break-even"}')
print(f'  {"50":<8} | {"32%":<13} | {"16 wins / 34 losses":<25} | {"+$50+"}')
print()
print('  Note: Win rate requirement increases with trade count due to spread costs')

print('\n### Actual Dollar Amounts Per Trade (Average):')
print()
print(f'{"Asset":<12} | {"Avg Win":<10} | {"Avg Loss":<10} | {"Win/Loss Ratio":<15} | {"Net Per Trade"}')
print('-'*70)
print(f'{"XAG_USD":<12} | {"$20.20":<10} | {"$8.13":<10} | {"2.48:1":<15} | {"+$7.61"}')
print(f'{"WHEAT_USD":<12} | {"$19.87":<10} | {"$8.00":<10} | {"2.48:1":<15} | {"-$0.16"}')
print(f'{"BCO_USD":<12} | {"$18.11":<10} | {"$7.35":<10} | {"2.46:1":<15} | {"-$0.56"}')

print('\n### Key Insight:')
print('  All strategies achieved PERFECT R:R execution (3.0 on wins, -1.0 on losses).')
print('  The difference in profitability comes down to WIN RATE:')
print()
print('  SUCCESS: XAG (55.6%) = Highly Profitable')
print('  STRUGGLE: WHEAT (28.1%) = Barely break-even after costs')
print('  STRUGGLE: BCO (26.7%) = Below profitability threshold')

print('\n### Balance Evolution Summary:')
print()
print('XAG_USD:  $360 -> $428.48 (+19.02%)')
print('  Peak: $428.48 | Max Drawdown: -5.96%')
print('  Steady growth with manageable drawdowns')
print()
print('WHEAT_USD: $360 -> $354.91 (-1.41%)')
print('  Peak: $411.13 | Max Drawdown: -16.51%')
print('  Volatile: Hit +14% then crashed to -1.41%')
print()
print('BCO_USD:  $360 -> $343.15 (-4.68%)')
print('  Peak: $362.69 | Max Drawdown: -17.99%')
print('  Devastating start: 10 losses, never recovered')

print('\n' + '='*80)
